### ISSUE TITLE
VCL Styles for Inno Setup, how to fix it?

### ISSUE THREAD

**Issue by ABAlA2015** [RRUZ/vcl-styles-plugins#16]
hi for everyone

VCL work fine in new script
but I have a problem in my old script, how to fix it?

![173456720](https://cloud.githubusercontent.com/assets/11780669/6987001/9fbe2836-da4b-11e4-9b2e-fea21d76468a.png)

my script

**Comment by RRUZ** [comment]
Please paste the full content of your script (.iss file)

**Comment by ABAlA2015** [comment]
I love you my brother :)

how to  send my script in private ? e-mail or how? , sorry I can't share :(

**Comment by RRUZ** [comment]
rodrigo.ruz.v at gmail.com

**Comment by ABAlA2015** [comment]
I send by outlook rodrigo.ruz@gimal.com or what ? :)

I don't have a gmail.com :)
