### ISSUE TITLE
Publish the new compiled InnoSetup plugin

### ISSUE THREAD

**Issue by DoCode** [RRUZ/vcl-styles-plugins#22]
Can you publish the new InnoSetup plugin, so we can use the new Windows 10 VCL styles?

**Comment by RRUZ** [comment]
The [Installer](http://goo.gl/Exkewk) of the plugin was updated a few days ago. On this page appears the download links  https://github.com/RRUZ/vcl-styles-plugins/wiki/Inno-Setup
