### ISSUE TITLE
Inno Setup's scroolbar in 'browse for folder' dialog does not work when vclstyles enabled

### ISSUE THREAD

**Issue by DoCode** [RRUZ/vcl-styles-plugins#24]
n/c
see it here in action:
![scroolbar-in-browse-for-folder-does-not-work-when-vclstyles-enabled_1_1](https://cloud.githubusercontent.com/assets/1489133/10824178/9eaf1f8c-7e5f-11e5-8c37-5f3e5a35f8a8.gif)

**Comment by RRUZ** [comment]
I just fixed this issue, please try the 1.5.4.0 version.

**Comment by DoCode** [comment]
Thanks. Works fine! :+1:
