### ISSUE TITLE
Can't view any of your themes

### ISSUE THREAD

**Issue by JohnnyKing94** [RRUZ/vcl-styles-plugins#27]
I'm using the demo script to test the themes, but everytime i load one team, it doesn't change nothing, i use your script, but nothing happens... same windows sking, same graphic with all the 30 themes. Do i need some required software/plugins to make it work or not?

**Comment by RRUZ** [comment]
Hi, are you using the NSIS or Inno Setup plugin?

**Comment by JohnnyKing94** [comment]
I'm using the Inno Setup plugin with Inno Setup Compiler 5.5.6 installed

**Comment by RRUZ** [comment]
This it seems related to the use of the *LoadVCLStyle* function. Check if you are using the ANSI or UNICODE version of Inno Setup and then Import the function *LoadVCLStyleW* for UNICODE or the *LoadVCLStyleA* method for the Ansi version

**Comment by JohnnyKing94** [comment]
Ok it was ANSI, resolved using "LoadVCLStyleA"... i suggest you to create a demo script for ANSI... just for not to panic people wondering what they did wrong...

**Comment by RRUZ** [comment]
Ok, I'm glad which your issue was resolved. Btw the [wiki of the project](https://github.com/RRUZ/vcl-styles-plugins/wiki/Inno-Setup) includes detailed instructions for use the plugin for ANSI and UNICODE versions of INNO Setup.
