### ISSUE TITLE
VclStylesinno.dll and Windows 10 Firewall Service

### ISSUE THREAD

**Issue by usermode** [RRUZ/vcl-styles-plugins#28]
I and other users who have updated to the last Windows 10 updates have troubles with launching vcl based inno installers with fully disabled Windows Firewall Service (after reboot).
I record flash movie with this bug, please see and try to reproduce it:
(Sorry for the Russian "example", I think You understand)
http://www.upload.ee/files/5517479/vcl_1540_win10_bug.zip.html
Note: this bug is happenned only on last 1.5.4.0. For 1.4.5.0 version all is good.

**Comment by RRUZ** [comment]
Sorry but I can't reproduce this issue, Also the plugin **doesn't** use the Firewall service or network access in any way.
