### ISSUE TITLE
New styles will not load

### ISSUE THREAD

**Issue by wkisielewicz** [RRUZ/vcl-styles-plugins#30]
Hi! 

It's probably more question. I have a problem with loading VCL Styles for Inno Setup. The installer generates correctly, but still remains an old style. 

Code:

```
[Files]
...
; add library to create new styles
Source: "VclStylesinno.dll"; DestDir: {app}; Flags: dontcopy
Source: "sepia.vsf"; DestDir: {app}; Flags: dontcopy

[Code]

// Import the LoadVCLStyle function from VclStylesInno.DLL
procedure LoadVCLStyle(VClStyleFile: String); external 'LoadVCLStyleW@files:VclStylesInno.dll stdcall';
// Import the UnLoadVCLStyles function from VclStylesInno.DLL
procedure UnLoadVCLStyles; external 'UnLoadVCLStyles@files:VclStylesInno.dll stdcall';

function InitializeSetup(): Boolean;
begin
   ExtractTemporaryFile('sepia.vsf');
   LoadVCLStyle(ExpandConstant('sepia.vsf'));
   Result := True;
end;
```
When I run the Inno Setup:

![extract](https://cloud.githubusercontent.com/assets/13674584/14527330/5f29d1cc-0249-11e6-8265-7e606e67cccc.png)

But my appearance installer does not change. I use Windows 8.1 64 bit, Inno Setup 5.5.6, VclStylesinno.dll version 1.5.4.0.

**Comment by Kotyarko** [comment]
Which version of Inno Setup you use?
If Ansi, then you must use:
`procedure LoadVCLStyle(VClStyleFile: String); external 'LoadVCLStyleA@files:VclStylesInno.dll stdcall';`

**Comment by wkisielewicz** [comment]
Yup i use Ansi.
It works! Thanks
