### ISSUE TITLE
Please bundle midas.dll for the Data Controls tab

### ISSUE THREAD

**Issue by guilt** [RRUZ/vcl-styles-plugins#32]
Hi,

I am unable to view the Data Controls tab in the VCL Style Viewer because midas.dll was not bundled. Please bundle this in your installers.

**Comment by RRUZ** [comment]
Hi,  please attach a image of the issue.

**Comment by guilt** [comment]
![midas](https://cloud.githubusercontent.com/assets/195178/16818545/e3dbbc9c-4965-11e6-93d0-a59df7a3e03b.Png)

**Comment by RRUZ** [comment]
I just added the _midas.dll_ file to the installers.

**Comment by guilt** [comment]
Yay!
