### ISSUE TITLE
[InnoSetup - 5.6.1 version] No skin applied

### ISSUE THREAD

**Issue by THedoux** [RRUZ/vcl-styles-plugins#47]
Hello,

With Innosetup 5.6.1 on a Win10 64 and the sample provided, there is no skin applied at all. 

The compiler is not producing error. 
Any idea what the problem could be? 

![compiler](https://user-images.githubusercontent.com/4609500/56972706-bf7fb080-6b6b-11e9-9fbc-7babbc861c8e.png)
![resultingWizard](https://user-images.githubusercontent.com/4609500/56972711-c1497400-6b6b-11e9-914e-ac71826ec1ac.png)

Thanks,

Tony

**Comment by THedoux** [comment]
It is perfectly working with the 5.5.9 version btw.

**Comment by LoicFr** [comment]
Hello, I think you didn't use the unicode version of Inno Setup. It works with it but not with the normal version (with no error listed).

**Comment by ab-tools** [comment]
Works perfectly fine also with the 5.6.1 ANSI version as long as you import the `LoadVCLStyleA` instead of the `LoadVCLStyleW` method as mentioned in the guide here:
https://github.com/RRUZ/vcl-styles-plugins/wiki/Inno-Setup
