### ISSUE TITLE
Windows 11 BETA, the interface will get stuck

### ISSUE THREAD

**Issue by sourcepowered** [RRUZ/vcl-styles-plugins#52]
When I clicked "Next", there would be no response, or the mouse would be crazy "circling", seems to be reading something. If I delete this plugin, there is no problem. So it should not be Inno's problem.

**Comment by ExtraviNull** [comment]
Same I also tested it on Windows 10 it worked just fine.

**Comment by ExtraviNull** [comment]
It will only crash on Windows 11 :(

**Comment by ExtraviNull** [comment]
> When I clicked "Next", there would be no response, or the mouse would be crazy "circling", seems to be reading something. If I delete this plugin, there is no problem. So it should not be Inno's problem.

I tested on NSIS it's not Inno's problem. I'm having the same issues.

**Comment by ExtraviNull** [comment]
Alright there is a new Windows 11 BETA, update today same issue still.

**Comment by sourcepowered** [comment]
Fixed. Don't using Delphi 10.2, using XE3 is best.
