### ISSUE TITLE
Is it possible to detect the PC Appearance?

### ISSUE THREAD

**Issue by ajtruckle** [RRUZ/vcl-styles-plugins#54]
Eg. Provide both Windows10 and Windows10Dark and based on the users current setting use the relevant theme?

**Comment by Nutzzz** [comment]
You can check the registry.  Read the REG_DWORD value "AppsUseLightTheme" in HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\
where:
0 = Dark
1 = Light
